# getting started with Jekyll on linux (ubuntu:)
# http://michaelchelen.net/81fa/install-jekyll-2-ubuntu-14-04/
# sudo apt-get install ruby ruby-dev make gcc nodejs
# install ruby 2.0+ : http://stackoverflow.com/questions/18490591/how-to-install-ruby-2-on-ubuntu-without-rvm
# sudo gem install jekyll --no-rdoc --no-ri
# sudo gem install jekyll-sitemap jekyll-paginate jekyll-gist
# (didn't work for me, doesn't seem necessary--requires ruby 2.2.2) sudo gem install github-pages --no-rdoc --no-ri

# to test locally, run (windows):
# bundle exec jekyll serve --baseurl
# on ubuntu:
# jekyll serve
title:            Dr. G
description:      Nate G's personal site
disqus_shortname: wordsforthewise
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally, set url to blank or use http://localhost:8888 , for production: //nateGeorge.github.io
url: http://localhost:8888 #//nateGeorge.github.io #http://localhost:8888 # for testing, use: http://localhost:8888 otherwise, //nateGeorge.github.io
baseurl: #/nateGeorge.github.io # make this line blank for testing... otherwise, /nateGeorge.github.io

# Owner/author information
owner:
  name:           Nate G
  avatar:         avatar.jpg
  bio:            "I'm a PhD chemical engineer by training, who does a lot of coding, electrical engineering, and chemistry."
  email:          nathancgeorge@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:         nateGeorge
  stackexchange:  http://stackexchange.com/users/5764261/wordsforthewise
  linkedin:       nateG-ai
  instagram:
  flickr:
  tumblr:
  google_plus:    +NathanGeorge-aesir

# Background image to be tiled on all pages
background: bg2.png

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-53388616-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

excerpt_separator: <!--more-->
